### ISSUE TITLE
How to add

### ISSUE THREAD

**Issue by aadamsx** [npvn/meteor-material-design#1]
How do you add this to Meteor 0.9.3 with the $ meteor add [package_name] command?

**Comment by npvn** [comment]
Hi Aaron,

I haven't published this package on atmosphere yet, so you'll need to manually copy the package into `/packages` and run `meteor add [package_folder_name]`.

At the moment I'm working on an alternative approach for this package. We'll no longer use template such as `{{Input}}` since people would have to change a lot of parts in their existing templates. With the upcoming version you can just install the package and see everything turned into material design. Stay tuned!

**Comment by aadamsx** [comment]
Thanks.  But how does this package relate to the meteor-polymer package?  How do Material Design and Polymer relate to each other (Polymer paper and core)?  My goal is to build a site that looks and feels like Material design (with a grid and reactivity).  Will this package provide me with the tools I need or do I need Polymer too?  How does Bootstrap fit in to all this?
